### ISSUE TITLE
Feed keeps restarting

### ISSUE THREAD

**Issue by rolfkokkeler** [craftcms/feed-me#524] opened 2019-04-26 08:40 UTC
### Description
The larger feeds ( >100 items  ) keep restarting without errors.
One of the feeds had 301 nodes, the feed stops importing after about 200 nodes, no errors.
After a while the feed restarts and starts importing from node#1 again, and stops after about 200 nodes.
There a no errors in the feedme log.

This is the feed-me config file:
```
return [
    '*' => [
        'compareContent' => true,
        'sleepTime' => 1,
        'logging' => 'errors',
        'queueMaxRetry' => 2,      
    ]
];

```

devmode craft disabled

### Additional info

- Plugin version: 4.1.0
- Craft version: 3.1.24

**Comment by rolfkokkeler** [comment] 2019-04-26 11:14
update:
I changed some matrix fields to type table or type entry, adjusted the feed settings.
The feed now imports all nodes, no errors.

In our case the matrix fields are not necessary, we can rewrite the code for retrieving the new data.
However, if this is not possible, the issue seems to be type matrix fields.

**Comment by angrybrad** [comment] 2020-11-06 21:30
Did some testing and not able to reproduce... guessing this is environment-specific. Going to go ahead and close it out, but comment back if it's still an issue.

**Closed by angrybrad** 2020-11-06 21:30 UTC
