### ISSUE TITLE
Ability to skip search index updating when importing feeds

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/feed-me#649] opened 2020-01-09 18:55 UTC
Once Craft 3.4 is out, Feed Me should be updated with an option to prevent search indexes from getting updated when importing a feed.

See https://github.com/craftcms/cms/issues/4840#issuecomment-540097211 and https://github.com/craftcms/cms/issues/5397.

**Comment by piotrpog** [comment] 2020-10-30 21:57
Hi!
Any progress on this?

**Comment by jasondibenedetto** [comment] 2021-01-06 03:12
Just wanted to bump this one to see if there has been any progress on this.

**Comment by juanjosezg** [comment] 2021-03-10 17:32
Any progress?

**Comment by OwenMelbz** [comment] 2021-03-16 12:13
We're struggling with this, server is falling over trying to process so many jobs - any temp work arounds?

![image](https://user-images.githubusercontent.com/1094740/111307189-ffad8680-8650-11eb-869f-94822d17cf1f.png)

**Comment by angrybrad** [comment] 2021-03-18 00:22
Anyone want to test this branch out? https://github.com/craftcms/feed-me/tree/feature/search-indexing

It adds support for disabling updating search indexing on a per-feed basis.

**Comment by limesquare-nl** [comment] 2021-05-10 08:38
> Anyone want to test this branch out? https://github.com/craftcms/feed-me/tree/feature/search-indexing
> 
> It adds support for disabling updating search indexing on a per-feed basis.

It looks like the branch is missing a migration.

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updateSearchIndexes' in 'field list'

**Comment by angrybrad** [comment] 2021-05-11 03:20
@limesquare-nl whoops - just pushed a commit that bumps the plugin schema version. if you pull latest, you should get prompted to run migrations.

**Comment by angrybrad** [comment] 2021-05-12 21:55
@OwenMelbz to confirm, you ran the migration after the schema version bump on the last commit?

**Comment by OwenMelbz** [comment] 2021-05-13 06:36
Hi,

Yeah I posted the composer json with like "dev-disable-updating" or whatever the branch was 😂 then composer update.

Then ran all the normal migrate commands, cleared caches, updating project yaml etc.

Everything seemed to be working until we ran the feed which took like 0.2 seconds which looked very suspicious, then when checked the logs we could see was erroring

**Comment by angrybrad** [comment] 2021-05-13 22:01
@OwenMelbz any chance could send a database dump and your composer.json file to support@craftcms.com and point us to which feed we could try to reproduce with locally?

**Comment by OwenMelbz** [comment] 2021-06-23 08:53
Hi @angrybrad I believe we'd spoken with Ollie about this a few weeks-months ago but still found it unresolved.

I've sent a WeTransfer of the site and the .json file we're importing to feed me to the email provided - The DB dump is within the "scripts/install.sql" folder.

If you could let us know if this works - Thanks

**Comment by angrybrad** [comment] 2021-06-29 00:07
@OwenMelbz I've merged in Oli's latest fix - want to give this branch a whirl again?

**Closed** 2021-08-08 23:03 UTC
Labels: enhancement
