### ISSUE TITLE
Class 'craft\feedme\base\ElementEvent' not found

### ISSUE THREAD

**Issue by JMKelley** [craftcms/feed-me#565] opened 2019-06-23 23:10 UTC
### Description

I have the following Module loaded into my system, following the Event's on the FeedMe documentation I've implemented the following to change the slug per entry import but unfortunately, it's returning a strange error that I just can't fix.

> Class 'craft\feedme\base\ElementEvent' not found - Element.php: 58

### Steps to reproduce

1. Create Module 
2. Use the below code:

```<?php

namespace modules;

use Craft;

use craft\feedme\base\Element;
use craft\feedme\events\ElementEvent;
use craft\feedme\services\Process;
use craft\feedme\events\FeedProcessEvent;


use yii\base\Event;

use craft\helpers\ElementHelper;
use craft\elements\Category;
use craft\elements\Entry;


class TitleChangerModule extends Module
{
    public function init()
    {
        parent::init();
        Event::on(
          Process::class,
          Process::EVENT_STEP_BEFORE_ELEMENT_SAVE,
          function(FeedProcessEvent $event) {
            switch($event->feed['name']){
                case 'merchants':
                    $element = $event->element;
                    $element->slug = Element::createSlug($element->title.' '.'Test Slug Addition');
                    break;
            }
        });
    } // Close Public Function
} // Close Module Off```

### Additional info

- Plugin version:
4.1.0
- Craft version:
3.1.31

**Comment by engram-design** [comment] 2019-06-23 23:18
Duplicate of https://github.com/craftcms/feed-me/issues/563 

FYI, should be fixed in https://github.com/craftcms/feed-me/pull/566

**Closed** 2019-07-06 14:08 UTC
