### ISSUE TITLE
Importing 'enabled' Status doesn't work for non-Primary sites

### ISSUE THREAD

**Issue by lcarcone** [craftcms/feed-me#1113] opened 2022-04-13 09:32 UTC
### Description
We have a multi-site implementation with a Primary site in English and other sites in different languages.
When we try to import entries for a 'Target Site' that is not the Primary site, the status of the entries is not set to 'Enabled' for the Target site while 'Status' is set to 'Use default value' in the Feed and the default value is set to 'Enabled'.
In this case, the status is set to 'Enabled' for the Entries of the Primary Site.

As we are trying to import thousands en entries on non-Primary sites, it is impossible to manually set the status of each ones.
And when we import an entry in a translated site (a non-Primary site) that doesn't match an entry on the Primary site (English), it is the entry of the Primary site that gets enabled, even though it contains the content translated.

### Steps to reproduce
Existing Feed
Step 1:
Feed Type: CSV
Element Type: Entry
Section: News Articles
Entry Type: Legacy (imported entries)
Target Site: Chinese (non-primary site)

Import strategy
x Create new elements 
x Update existing elements 
   Disable missing elements globally 
   Disable missing elements in the target site 
   Delete missing elements 
x Update search indexes

Step 3 (Map)
...
Status: Use default value (Enabled)

### Behavior
The status is not set to 'Enabled' for the Chinese site entries but for the Primary site entries

### Additional info

- Craft version: 3.7.32
- Feed Me version: 4.4.1.1
- PHP version: 7.4.28
- Database driver & version: MariaDB 10.3.34-MariaDB-0+deb10u1 Debian 10

**Comment by angrybrad** [comment] 2022-05-05 00:16
Closing as a dupe of https://github.com/craftcms/feed-me/issues/822

**Closed by angrybrad** 2022-05-05 00:16 UTC
Labels: bug, duplicate
