### ISSUE TITLE
Last updated date touched even if no fields changed (triggering sitemap updates)

### ISSUE THREAD

**Issue by gbowne-quickbase** [craftcms/feed-me#1246] opened 2023-02-28 19:25 UTC
### Description
Even if no datapoints change in an entry, the last updated date is being set for each item when Feedme runs. The downstream effect of this is for users who have NYStudio107's SEOMatic plugin running sitemaps, since those will see a new date, generate an updated sitemap, and submit it to google. There's no new version created because there's nothing to update. Can we have it not update these if nothing changes? 

(If authors are using this to determine the last time a feed ran, maybe this should be on the Feedme page itself?)

### Steps to reproduce

1. Run a feed where "Update items" is checked and items are properly keyed to allow for updates
2. See the last updated change on imported items even if no data changed

### Additional info

- Craft version: 3.7.65.2
- PHP version: 7.4.33
- Database driver & version: MySQL 5.7.33
- Plugins & versions: (relevant added)
  - Feedme 4.5.4
  - SEOMatic 3.4.49

**Comment by kristiansp** [comment] 2023-04-08 18:37
I don’t have a fix as such, but a question, what does the Feed Me logs say is updating? I have seen that if one of the fields effectively is an array (like entries field, etc), Feed Me doesn’t sort the arrays before comparing them, so two arrays with the same items can cause an update, because they have a different order.

I have a PR for this #735, it’s a simple fix, but will of course break on updates if you apply it.

**Comment by i-just** [comment] 2023-06-20 10:44
Hi, thanks for getting in touch. I can’t replicate this behaviour. 

Some improvements around checking if the values have changed have recently been made (v4.6.0 and v5.1.0).

I will close it now, but if you have a replicable scenario, please feel free to post the details, and we’ll look into it. A snippet of the feed and a screenshot of the mapping screen are always welcome, as they usually help reproduce the behaviour.

**Closed by i-just** 2023-06-20 10:44 UTC
Labels: bug
