### ISSUE TITLE
Importing multiple child entries into an Entries field uses first child's field values for all remaining children

### ISSUE THREAD

**Issue by amphibian** [craftcms/feed-me#1227] opened 2023-01-31 22:39 UTC
### Description

When importing into an Entries field (creating child entries), the mapped **Title** for each element is correctly saved, but the additional fields (in my case, simple text fields) are not, instead saving the _first_ child entry's data to those fields in all subsequent children.

Of note, the primary element I am importing is a Commerce Product, and the Entries field in question is assigned to that product type.

### Field Mapping:

<img width="775" alt="Screenshot 2023-01-31 at 4 33 50 PM" src="https://user-images.githubusercontent.com/53333/215899295-41377fc7-0d8f-4752-826a-d037871b73cc.png">

### Field Result:

<img width="271" alt="Screenshot 2023-01-31 at 4 34 51 PM" src="https://user-images.githubusercontent.com/53333/215899315-d72e2fdb-9e31-4483-92de-449e6dd58600.png">

(Titles are correct.)

### Content Result:

<img width="826" alt="Screenshot 2023-01-31 at 4 34 35 PM" src="https://user-images.githubusercontent.com/53333/215899326-b668054f-3bf1-4e66-9331-f19e518f78eb.png">

(2nd and 3rd fields are incorrect.)

### Additional info

- Craft version: 4.3.6.1
- PHP version:8.0.8
- Plugins & versions: Feed Me 5.0.5

**Comment by i-just** [comment] 2023-02-20 15:59
Hi, thanks for getting in touch. The issue is likely to do with how your feed data is formatted. 
I believe you’re using something along those lines, and I can replicate this behaviour with this JSON markup:
```
{
  "entries": [
    {
      "title": "test1",
      "authors": [
        {
          "author": {
            "name": "Person 1",
            "keyname": "person1",
            "bio": "Bio for person 1"
          }
        },
        {
          "author": {
            "name": "Person 2",
            "keyname": "person2",
            "bio": ""
          }
        },
        {
          "author": {
            "name": "Person 3",
            "keyname": "person3",
            "bio": "Bio for person 3"
          }
        }
      ]
    }
  ]
}
```

but if I switch to:
```
{
  "entries": [
    {
      "title": "test1",
      "authors": [
        {
          "name": "Person 1",
          "keyname": "person1",
          "bio": "Bio for person 1"
        },
        {
          "name": "Person 2",
          "keyname": "person2",
          "bio": ""
        },
        {
          "name": "Person 3",
          "keyname": "person3",
          "bio": "Bio for person 3"
        }
      ]
    }
  ]
}
```
then the inner element fields are mapped correctly.

One more thing to mention is that, in this case, keeping all fields you want to map in the feed is important. If I was to remove `"bio": ""` from `Person 2` node, the `bio` data for `Person 3` would get shifted by one (it would be assigned to `Person 2`, and `Person 3` bio would be empty.

I hope this helps you. I’m going to go ahead and close this, but please feel free to reply if you have any further questions.

**Comment by amphibian** [comment] 2023-02-21 18:03
Thanks for the reply Iwona. But with this change I am still encountering the bug, and I think it's because we're not quite testing the same thing. My fault, since I realize now I failed to clarify my setup in my initial report.

My "authors" field is not an **Entries** field, but a **Matrix** field. Within that Matrix field is a block type which then contains an Entries field and an additional "Role" field (dropdown).

This is why I structured my JSON in this manner:

```
{
	"entries": [
		{
			"title: "Name of my book",
			"authors": [ <-- Matrix field
			  {
				"author": { <-- Entries field
					"bio": "<p>Delia Gavrus is an Associate Professor in the Department of History at the University of Winnipeg. </p>",
					"keyname": "Gavrus",
					"name": "Delia Gavrus"
				},
				"role": "B01"
			  },
			  {
				"author": {
					"bio": "<p>James Hanley is a Professor of History at the University of Winnipeg. </p>",
					"keyname": "Hanley",
					"name": "James Hanley"
				}
				"role": "B01"
			  }
			]
		}
	]
}
```

But even if I remove that extra object layer (which I can, because I'm only associating one author entry inside each block), the duplication of the field values form the first Matrix block remains. Example JSON:

```
{
	"entries": [
		{
			"title: "Name of my book",
			"authors": [
			  {
				"bio": "<p>Delia Gavrus is an Associate Professor in the Department of History at the University of Winnipeg. </p>",
				"keyname": "Gavrus",
				"name": "Delia Gavrus"
				"role": "B01"
			  },
			  {
				"bio": "<p>James Hanley is a Professor of History at the University of Winnipeg. </p>",
				"keyname": "Hanley",
				"name": "James Hanley"
				"role": "B01"
			  }
			]
		}
	]
}
```

**Comment by i-just** [comment] 2023-02-21 18:15
Right, sorry, looks like I got confused somewhere along the way. Reopening.

**Comment by angrybrad** [comment] 2023-04-13 18:35
Resolved in https://github.com/craftcms/feed-me/pull/1278 for the next FeedMe v4 and v5 release.

**Closed by angrybrad** 2023-04-13 18:35 UTC
Labels: bug
