### ISSUE TITLE
TypeError when trying to import delimited string on PHP 8.1.18

### ISSUE THREAD

**Issue by meinhard-meintjes** [craftcms/feed-me#1308] opened 2023-04-28 10:06 UTC
### Description

Feedme seems to have an issue when exploding delimited string values like "filename1.jpg|filename2.jpg" when using PHP 8.1.18.
I get an error "TypeError: array_merge(): Argument #1 must be of type array, null given" in DataHelper.php::89
If, in DataHelper.php::65, I change the default value of $value to [], then it works as expected.

### Steps to reproduce

1. Use PHP 8.1.18
2. Install Feedme
3. Set up a feed that contains a string field (containing delimited filenames with extension) delimited by custom delimiter like '|' (e.g. "filename1.jpg|filename2.jpg")
5. Import feed

### Additional info

- Craft version: 4.4.6.1
- PHP version: 8.1.18
- Plugins & versions: FeedMe = 5.1.2

**Comment by i-just** [comment] 2023-04-28 10:12
Hi, thanks for reaching out. Looks like a duplicate of #1298 (fixed for the next release), so I’m going to close this one. You can follow along on the initial report!

**Closed by i-just** 2023-04-28 10:12 UTC
Labels: bug, duplicate

**Comment by meinhard-meintjes** [comment] 2023-04-28 10:24
> Hi, thanks for reaching out. Looks like a duplicate of #1298 (fixed for the next release), so I’m going to close this one. You can follow along on the initial report!

Sorry, you're right. Thanks!
