### ISSUE TITLE
Image file duplicate when feed AWS S3 image assets

### ISSUE THREAD

**Issue by xhuang9** [craftcms/feed-me#355] opened 2018-07-19 03:54 UTC
### Description

Problem:
When using craft 3 AWS s3 assets plugin as an asset field inside craft entry, it will create a duplicate image file every time, when it tries to feed the asset.

Settings:
1. "Import strategy" to "Create", "Update".
2. We set the asset to read and from an AWS s3 bucket URL. 
3. Tick the "Create asset from URL, if not exists" checkbox.  
4. and in the drop down box we set "use existing assets". 

Result: 
Then I check the asset's folder, it created a new file with different date string after the original file. 

Original file:        original.jpg
New file:             original_2018_07_19_12_00_01.jpg

And in the craft database, it links the original file assets to this newly generated file with date string behind. 

It is OK, if that deletes the old assets, but system just let the file lying around. It does that every time, when I feed. So now I got a folder that full of those duplicates, taking large chunk of storage and massively slowing down the feed. (Each assets feed takes about 10 seconds to finish, I got thousands of assets in one feed.)

Is there a way to make feed me targeting the original assets and not generating those duplicates? 

### Steps to reproduce

1. Install craft AWS s3 plugin
2. Create an AWS s3 assets and create it as a field, (make sure set "Upload Location" not to any subfolder)
3. Add this field into a craft entry
4. Put an image into that folder and grab the public URL to feed this image to assets.
5. Set up feed: 
          "Import strategy" to "Create", "Update"
          In field map, put the URL of that image into field, and set that assets field "If exist" to "Use existing 
         asset"
6. Run feed
7. Check the asset's folder. To see whether the feed creates a duplicate image file with current date string.

### Additional info

- Plugin version:  3.0.0-beta.16
- Craft version:  3.0.15
- craftcms/aws-s3: ^1.0

**Comment by EternalBlack** [comment] 2019-03-19 10:08
We currently are experiencing the same issue. Seems to be unrelated to S3 Storage as this happens on local storage too. Our assets are getting flooded with duplicates as we got about ~50 feeds where each retrieves an image. All names the same, but got that timestamp at the end.

**Comment by engram-design** [comment] 2019-03-21 05:13
Struggling to reproduce this I’m afraid, so might need a little more information on your setups. Would you be able to install the latest branch, which includes additional logging for asset uploads.

You can install the latest branch via `composer require verbb/feed-me:dev-craft-3`.

After that, would you be able to submit a Help request through the plugin @xhuang9 ? Or, you're welcome to post the latest sections of the log file after running your feed again with this latest code.

**Comment by xhuang9** [comment] 2019-03-21 05:45
@EternalBlack 
We went around this issue by not handling assets in craft. We only let craft take plain-text of images URLs, and built a custom interface allow user upload directly to S3 bucket. Plus using some Lambda function to watching folders and do the auto crop on the fly.

@engram-design 
If I remember correct, it's the craft assets element's function handles the image save. Not a feed-me function. For detail check "craftcms/cms/elements/Asset.php".

**Comment by engram-design** [comment] 2019-03-21 06:17
@xhuang9 Yep, but its Feed Me's job to check for an existing asset (via filename) and use that instead of uploading a duplicate of it, or getting the behaviour that you're seeing (duplicating it, but not deleting the duplicate). I'll continue to see how far I get with the issue

**Comment by EternalBlack** [comment] 2019-03-23 09:17
So, I got some news about the image duplications with the new more verbose image logging:

```

Type | Message | Timestamp
-- | -- | --
info | P Psychotalk: Processing 1 elements finished in 2.63s | 3/23/2019 10:06 AM
error | P Psychotalk: Starting processing of node #1.Show detail | 3/23/2019 10:06 AM
info | ↳ P Psychotalk: Match existing element with data {"title":"Psychotalk"}. | 3/23/2019 10:06 AM
info | ↳ P Psychotalk: Existing element #53586 found. | 3/23/2019 10:06 AM
info | ↳ P Psychotalk: Search for existing asset with query {"siteId":"1","status":null,"folderId":1,"kind":["image"],"limit":"1","filename":"pt_logo_neu_1400x1400.jpg","includeSubfolders":true} | 3/23/2019 10:06 AM
info | ↳ P Psychotalk: Found 0 existing assets: [] | 3/23/2019 10:06 AM
info | ↳ P Psychotalk: Fetching remote image https://www.psycho-talk.de/pt/pt_logo_neu_1400x1400.jpg - pt_logo_neu_1400x1400.jpg | 3/23/2019 10:06 AM
info | ↳ P Psychotalk: Creating asset with content {"tempFilePath":"\/var\/www\/vhosts\/audionow.de\/invisiblestage.audionow.de\/storage\/runtime\/temp\/feedme\/pt_logo_neu_1400x1400.jpg","filename":"pt_logo_neu_1400x1400.jpg","newFolderId":"1","volumeId":"1","avoidFilenameConflicts":true,"scenario":"create","propagate":true,"conflict":"replace"} | 3/23/2019 10:06 AM
error | ↳ P Psychotalk: image - Asset error: https://www.psycho-talk.de/pt/pt_logo_neu_1400x1400.jpg - Trying to get property 'id' of non-object. | 3/23/2019 10:06 AM
```

The image is there 100% of the time. Being in the Admin Panel->Assets and doing a search for `pt_logo_neu_1400x1400.jpg` results in literally nothing though too. So Feed Me seems to be kind right, if `Craft` doesn't give it the result. Using `pt_logo_neu_1400x1400` (without file-ending) though results in a found asset.
I can't say for sure, why `Craft` itself isn't able to find it with the query, but this seems to be the root of the problem.

**Comment by engram-design** [comment] 2019-03-23 09:55
Thanks for the report back @EternalBlack. Have you tried running the search index through Utilities? That might help in indexing the content for assets (among other elements), as you're correct, if it can't find the asset by going to your Assets section and searching, then there might be something up with the search indexes.

**Comment by EternalBlack** [comment] 2019-03-25 08:01
Did some testing on the weekend. Updated the asset indexes and rerun everything multiple times. Still had some duplicates. Less than before but still some. The most strange part about it is, that I don't see the pattern yet as I ran all feeds 5 times -> Some assets are there 3 times, some 2, some 4 and the majority a single one (as expected).

**Comment by EternalBlack** [comment] 2019-04-08 11:17
Sorry for the late feedback. Got some new intel though.


> error | P Over My Dead Body: Starting processing of node #1.Show detail | 4/8/2019 12:51 PM
> -- | -- | --
> info | ↳ P Over My Dead Body: Match existing element with data {"feedurl":"https:\/\/rss.art19.com\/over-my-dead-body"}. | 4/8/2019 12:51 PM
> info | ↳ P Over My Dead Body: Existing element #77109 found. | 4/8/2019 12:51 PM
> info | ↳ P Over My Dead Body: Search for existing asset with query {"siteId":"1","status":null,"folderId":1,"kind":["image"],"limit":"1","filename":"b91e9453b129135b876807c6c8128ddf9a2d16a1a2f9ee42d16013c7bdc3444ab97f8bfe2d5c8fc65e96c339615029d9a952a79f6cb8e9ead01bee5a3437a22e.jpeg","includeSubfolders":true} | 4/8/2019 12:51 PM
> info | ↳ P Over My Dead Body: Found 1 existing assets: ["77108"] | 4/8/2019 12:51 PM
> info | ↳ P Over My Dead Body: Fetching remote image https://content.production.cdn.art19.com/images/a9/3c/66/11/a93c6611-0893-4f1f-b37f-78217d7a3360/b91e9453b129135b876807c6c8128ddf9a2d16a1a2f9ee42d16013c7bdc3444ab97f8bfe2d5c8fc65e96c339615029d9a952a79f6cb8e9ead01bee5a3437a22e.jpeg - b91e9453b129135b876807c6c8128ddf9a2d16a1a2f9ee42d16013c7bdc3444ab97f8bfe2d5c8fc65e96c339615029d9a952a79f6cb8e9ead01bee5a3437a22e.jpeg | 4/8/2019 12:51 PM
> info | ↳ P Over My Dead Body: Creating asset with content {"tempFilePath":"PATHTOCRAFT\/storage\/runtime\/temp\/feedme\/b91e9453b129135b876807c6c8128ddf9a2d16a1a2f9ee42d16013c7bdc3444ab97f8bfe2d5c8fc65e96c339615029d9a952a79f6cb8e9ead01bee5a3437a22e.jpeg","filename":"b91e9453b129135b876807c6c8128ddf9a2d16a1a2f9ee42d16013c7bdc3444ab97f8bfe2d5c8fc65e96c339615029d9a952a79f6cb8e9ead01bee5a3437a22e.jpeg","newFolderId":"1","volumeId":"1","avoidFilenameConflicts":true,"scenario":"create","propagate":true,"conflict":"replace"} | 4/8/2019 12:51 PM
> error | ↳ P Over My Dead Body: image - Asset error: https://content.production.cdn.art19.com/images/a9/3c/66/11/a93c6611-0893-4f1f-b37f-78217d7a3360/b91e9453b129135b876807c6c8128ddf9a2d16a1a2f9ee42d16013c7bdc3444ab97f8bfe2d5c8fc65e96c339615029d9a952a79f6cb8e9ead01bee5a3437a22e.jpeg - finfo_file(PATHTOCRAFT/storage/runtime/temp/feedme/b91e9453b129135b876807c6c8128ddf9a2d16a1a2f9ee42d16013c7bdc3444ab97f8bfe2d5c8fc65e96c339615029d9a952a79f6cb8e9ead01bee5a3437a22e.jpeg): failed to open stream: No such file or directory. | 4/8/2019 12:51 PM
> info | ↳ P Over My Dead Body: Search for existing entry with query {"siteId":"1","status":null,"sectionId":[11],"limit":"","where":["=","field_guid","gid:\/\/art19-episode-locator\/V0\/8h3cLE4ag98DwpZ3fwl3KMuDukd9_EfEWy48R-jNEaM"]} | 4/8/2019 12:51 PM
> info | ↳ P Over My Dead Body: Found 1 existing entries: ["77099"] | 4/8/2019 12:51 PM
> info | ↳ P Over My Dead Body: Search for existing entry with query {"siteId":"1","status":null,"sectionId":[11],"limit":"","where":["=","field_guid","gid:\/\/art19-episode-locator\/V0\/a1Xc8RzR2TX2gi4Pe6GQkuDu96Ml0FS8ozpHaZRP9_E"]} | 4/8/2019 12:51 PM
> info | ↳ P Over My Dead Body: Found 2 existing entries: ["77099","77100"]
> ... | ...

The re-index before really helped to narrow it down but this seems to be a problem. I can confirm that this is neither a problem of long filename nor ones with special characters as this also happens to:

> info | ↳ P The Big Pond: Creating asset with content {"tempFilePath":"PATHTOCRAFT/storage\/runtime\/temp\/feedme\/thebigpond.jpg","filename":"thebigpond.jpg","newFolderId":"1","volumeId":"1","avoidFilenameConflicts":true,"scenario":"create","propagate":true,"conflict":"replace"} | 4/8/2019 1:03 PM
> -- | -- | --
> error | ↳ P The Big Pond: image - Asset error: http://goethe.akamaized.net/podcast/ins/us/tbp/thebigpond.jpg - finfo_file(PATHTOCRAFT/storage/runtime/temp/feedme/thebigpond.jpg): failed to open stream: No such file or directory. | 4/8/2019 1:03 PM
> info | ↳ P The Big Pond: Search for existing entry with query {"siteId":"1","status":null,"sectionId":[11],"limit":"","where":["=","field_guid","http:\/\/goethe.akamaized.net\/podcast\/ins\/us\/tbp\/thebigpond22_wolfgang-karg_irene_bilal_the-story-of-the-brezn_long.mp3"]}

I may went nuts with the feeds import though (i.e. hitting `run feed` to open in a new tab multiple times really fast). Whats really interesting is though is that the second one (`The Pond`) now has an image asset that is only loaded half way [half way](https://ibb.co/PjTDZ3R) through (used `preview` too, it's really only loaded half way). I already might even suspect that this is a conflict between feed me trying to handle the image and [craft-colorextracor](https://github.com/born05/craft-colorextractor) intervening.

**Comment by EternalBlack** [comment] 2019-04-09 10:27
I can confirm that using `ASYNC_QUEUE_CONCURRENCY=1` (running only 1 task at a time) results in 0 duplicates. So there seems to be a problem with shared resources among tasks. Unfortunately running 1 task at a time also takes really long for ~200 feeds...

**Comment by leevigraham** [comment] 2020-04-15 05:21
Did this ever get resolved? I'm importing 13k images and there's heaps of duplicates. I'm not using the async queue plugin.

**Comment by EternalBlack** [comment] 2020-04-15 06:08
@leevigraham we ended up ditching FeedMe and build our own module for the importing stuff where we have more fine grained control on how the outcome is (regarding naming and business logic) at the cost of "flexibility/easy of use" that FeedMe has.

**Comment by leevigraham** [comment] 2020-04-15 06:20
@EternalBlack In my case I think it's because I fired up multiple php processes via command line and admin that were stepping over each other. In my case I'm only playing around so it's not a big deal. If I this was a production project I would probably do the same thing and write my own importer :)

**Closed** 2020-11-16 01:42 UTC
