### ISSUE TITLE
Can't update some Entries' fields with blank data

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/feed-me#1162] opened 2022-06-23 15:05 UTC
### Description
I would like to import and update Entries using a FeedMe, based on a remote JSON file. Sometimes, the fields are filled, sometimes not.

I would like FeedMe to update these fields if they are empty in the JSON. But currently, these blank values are skipped instead of replaced.

For special field like Date/Time field, I need a true blank value, not the current date.

Is this possible at this time? If so, how can I do?

### Additional info

- Craft version: Craft Pro 3.7.43
- PHP version: 7.4.25
- Database driver & version: MySQL 5.7.23

**Comment by jamesmacwhite** [comment] 2022-06-23 15:52
Related: https://github.com/craftcms/feed-me/issues/797

**Comment by angrybrad** [comment] 2023-04-11 17:20
Closing as a dupe of https://github.com/craftcms/feed-me/issues/797, which has been resolved (for real this time) in the next release.

**Closed by angrybrad** 2023-04-11 17:20 UTC
Labels: bug
