### ISSUE TITLE
Problem importing data into Money field

### ISSUE THREAD

**Issue by nilsenpaul** [craftcms/feed-me#1315] opened 2023-05-10 11:33 UTC
### Description
I'm trying to import data into a Money field, but I can't seem to figure out the 'correct' way to do so. Examples:

- Input `1.274,00` works fine, money field shows `€ 1.274,00`
- Input `89,99` turns into `€ 8.999,00` in money field
- Input `7,99` turns intro `7,99`, so that's correct

What format should the input have, to get correct results?

### Additional info

- Craft version: 4.4.8
- PHP version: 8.1
- Feed Me version: 5.1.3

**Comment by nilsenpaul** [comment] 2023-05-16 07:43
So, I tried to figure out what happens to which field. I created a clean install of Craft, Commerce and FeedMe. Same versions, etc. CMS language and formatting locale are set to Dutch. Commerce currency is set to EUR.

Products have a custom money field (set to EUR), and of course the 'default' price field. Now, I created a CSV file and altered that before each FeedMe import. Both fields (variant price and the custom money field) are mapped to the 'Bedrag' column of the CSV. The results are as follows:

<img width="591" alt="Scherm­afbeelding 2023-05-16 om 09 35 10" src="https://github.com/craftcms/feed-me/assets/6794819/8b2dbc53-cbdf-45e6-9882-0d9951935938">

So, I could not find a way to let the price field and the custom money field import equal data, even though the input comes from the same column. How should we fix this?

**Comment by i-just** [comment] 2023-06-16 10:43
Hi, thanks for getting in touch and for all the info! The issue you’re experiencing is caused by your feed having numbers represented as strings.

If you change the numbers to actual numbers in the feed, the results will be consistent between the price and money fields. For example, use `Test 1,1274.00` instead of `Test 1,"1274.00"`

Now, the above “trick” will work for, e.g. CSV and JSON, but not for XML feed. I’m looking into it further, but I wanted to share this part of my findings asap.

**Comment by angrybrad** [comment] 2023-06-26 03:27
Resolved via https://github.com/craftcms/feed-me/pull/1331 and will be included in the next release.

**Closed by angrybrad** 2023-06-26 03:27 UTC
Labels: bug
