### ISSUE TITLE
toLowerCase() must be of the type string in AssetHelper.php

### ISSUE THREAD

**Issue by saatchinorway** [craftcms/feed-me#791] opened 2020-12-30 08:48 UTC
### Description
When importing an XML feed, some entries fail with the following error message:

`Argument 1 passed to craft\helpers\StringHelper::toLowerCase() must be of the type string, null given, called in [project-name]/vendor/craftcms/feed-me/src/helpers/AssetHelper.php on line 358 - StringHelper.php: 1639`

Downgraded to 4.2.4 and the same XML feed imports, but without image attachment.

### Steps to reproduce

Import an entry that has a file attachment / image _without_ an extension, for example an image called just `image` in stead of `image.jpg`

Managed to work around this by adding an extension to the affected file names, but this should be fixed for those cases where it is not possible to change the source. If file extensions are needed they could be added based on the file's MIME type.

### Additional info

- Craft version: 3.5.17.1
- PHP version: 7.4.2

**Comment by green17** [comment] 2021-01-11 11:27
This bug is happing to us too where files are in the import as /files?p_Doc_Ref=PF106018&p_File_Type=rendition_4000_png for eg.

**Comment by angrybrad** [comment] 2021-02-22 18:32
@saatchinorway @green17 can one of you share a full stack-trace leading up to the error?

**Comment by angrybrad** [comment] 2021-03-05 00:28
I couldn't reproduce this exact error, but I did hit another one that was actually a Craft bug that I just [pushed a fix](https://github.com/craftcms/cms/commit/1391b09d54e98eb5d20adc81632e523c30b50e12) for that resolve this in Feed Me after the next Craft release.

**Closed by angrybrad** 2021-03-05 00:28 UTC
Labels: bug

**Comment by green17** [comment] 2021-03-05 08:16
Thanks @angrybrad, apologies somehow missed your request for full stack-trace we formated the XML feed coming in to have a .png at the end which seemed to fix this.
