### ISSUE TITLE
Unable to match an existing element. Have you set a unique identifier for ["title"]?

### ISSUE THREAD

**Issue by JMKelley** [craftcms/feed-me#786] opened 2020-12-14 12:57 UTC
### Description

> Unable to match an existing element. Have you set a unique identifier for ["title"]? Make sure you are also mapping this in your feed and it has a value. - Element.php: 160

Updated last night to the latest version, I am receiving this error on feeds that previously worked perfectly for me. Nothing customised, just importing a basic JSON feed. 

- [X] Supplied a Title Field in my Feed Setup
- [X] Unique Identifier is the Default "Title"

### Steps to reproduce

1. Update to the latest FeedMe
2. Create a JSON feed importing Entries.
3. Set the feed to Add & Update.
4. Supply content for the "Title" field.
5. Run Feed.

### Additional info

- Craft version: 3.5.16
- PHP version: 7.4.8
- Database driver & version: MySql
- Plugins & versions: FeedMe, Retour, Blitz, SEOMatic (Latest on all)

### Example Feed Data

```
 "items": [
        {
            "item": {
                "terms": null,
                "offerCode": null,
                "offerType": "deal",
                "created": "2020-12-14",
                "merchant_name": "Macy's",
                "validFrom": "2020-12-13T00:00:00.000Z",
                "categories": [
                    {
                        "name": "Health & Beauty",
                        "id": "4707eb2d-eec6-53c3-a3ec-ccca769986a6"
                    },
                    {
                        "name": "Technology & Electrical",
                        "id": "2df28bc0-b066-5178-ac52-16691afa789d"
                    }
                ],
                "id": "001da77c-716c-58c0-b0b0-c6f42091cb07",
                "title": "40% Off Women's Designer Coats. Shop Now at Macys.com plus Free Curbside Pickup! Valid 12/13 Through 12/19!",
                "validTo": "2020-12-21T00:00:00.000Z"
            }
        },
        {
            "item": {
                "terms": null,
                "offerCode": null,
                "offerType": "deal",
                "created": "2020-12-14",
                "merchant_name": "Macy's",
                "validFrom": "2020-12-13T00:00:00.000Z",
                "categories": [
                    {
                        "name": "Health & Beauty",
                        "id": "4707eb2d-eec6-53c3-a3ec-ccca769986a6"
                    }
                ],
                "merchant_id": "808bb5a7-e3c9-5eeb-ae85-70f325950ce9",
                "title": "Special 40% INC Plaid Puff-Sleeve Top, Created for Macy's. Shop Now at Macys.com Plus Free Curbside Pickup! Valid 12/13 Through 12/17!",
                "validTo": "2020-12-18T00:00:00.000Z"
            }
        },
```

**Comment by JMKelley** [comment] 2020-12-14 16:04
Works on Rollback to previous version.

**Comment by angrybrad** [comment] 2020-12-14 18:34
@JMKelley any chance you could send a db dump and your composer.json file to support@craftcms.com?

**Comment by JMKelley** [comment] 2020-12-14 20:48
I've just tested it on a fresh install, getting the same error. I can send
the api url if needed.

**Comment by angrybrad** [comment] 2020-12-14 21:18
@JMKelley pretty sure https://github.com/craftcms/feed-me/commit/482e0db276c65e3c03b7b47e8d8efda824d583fb resolves it if you want to give it a whirl with your setup

**Comment by astuteo** [comment] 2021-02-12 18:52
@JMKelley Just wondering if Brad's fix resolved your issue? I'm running into the same thing on various feeds, but I'm on 4.3.5.1 already.

**Comment by JMKelley** [comment] 2021-02-12 19:18
I didn't update my plugin. Rolled it back to the stable version. I'd report
it to brad if it's still not working

**Comment by astuteo** [comment] 2021-02-12 19:23
@angrybrad This could totally be user error (because it's me), but I'm having this same issue. In particular when trying to parse elements that feature only one value but formatted as if it were an array. This screenshot is from the FDA's JSON feed as an example.
![image](https://user-images.githubusercontent.com/375880/107812308-1c465e00-6d35-11eb-95e8-feb2c2589a92.png)

**Comment by angrybrad** [comment] 2021-02-22 18:04
@astuteo can you shoot a database dump and composer.json file over to support@craftcms.com and reference this issue? Want to make sure I'm testing with your exact settings.

**Comment by angrybrad** [comment] 2021-02-22 22:43
@JMKelley what version did you roll back to make it work? Not sure if you're hitting the exact same issue as I think his is related to the first "meta" node in the feed. In your feed settings, are you mapping to the root "items" or the "item" child nodes for the primary elements?

**Comment by angrybrad** [comment] 2021-02-22 23:22
@astuteo actually, I think yours is basically the same. The feed's primary element is mapped over to `/root`, but pretty sure you want `/results/submissions`?

**Comment by astuteo** [comment] 2021-02-23 01:29
@angrybrad No, in this case I actually do need the two items from root. While not titled, each item has multiple "submissions". I did try setting the Craft title input to one of the subfields so that it would surely have a value to input, but it still fails.

**Comment by JMKelley** [comment] 2021-02-23 12:30
@angrybrad I rolled back to 4.3.2. Works like a charm for me. Might be worth rolling back to this version @astuteo

**Comment by angrybrad** [comment] 2021-02-23 15:46
@JMKelley In your feed example, are you mapping to the root "items" or the "item" child nodes for the primary elements?

**Comment by JMKelley** [comment] 2021-02-23 16:08
Items

**Comment by angrybrad** [comment] 2021-02-23 23:58
@astuteo sorry if I'm being dense, but in your example:

https://api.fda.gov/drug/drugsfda.json?search=openfda.manufacturer_name:%22heron+therapeutics%22&limit=1000

Your "primary element" was set to `/root`, which would match the first-level nodes of "meta" and "results".

> While not titled, each item has multiple "submissions".

Seems like `/results/submissions` is what you're interested in, then?  When I changed the primary element to that and setup a field mapping (because there was none setup), the import ran fine for me with the database back you provided.

**Comment by angrybrad** [comment] 2021-02-24 00:09
@JMKelley Did you ever send a database dump and composer.json to support@craftcms.com? If so, haven't a hard time finding it, could you resend them? The only way I can reproduce it with my test setup is similar to @astuteo's setup... if I set it to `/root`, I'll get the error, but if I set it to `/items`, it works regardless if it's 4.3.2 or the latest.

But the example feed data you initially provided is invalid JSON, so I might have made some assumptions about how it's formatted when trying to correct it. So if you could send the exact feed over too, that'd help.

**Comment by astuteo** [comment] 2021-02-24 02:29
@angrybrad No worries, maybe this will help. Below is the specific data I need from the feed. There are two drugs, both are listed under `/root`. When I pull up the `/results/submissions` element, it doesn't contain the data below.

application_number: NDA022445
brand_name: SUSTOL
generic_name: GRANISETRON
dosage_form: INJECTION, EXTENDED RELEASE
manufacturer_name: Heron Therapeutics

application_number: NDA209296
brand_name: CINVANTI
generic_name: APREPITANT
dosage_form: EMULSION
manufacturer_name: Heron Therapeutics

Are you able to feed this specific into my DB, or is it only available under `/root`? On my end everything structurally makes sense when I browse the feed. There are two items I need, they match up correctly in the admin, but error out when I run the feed.

**Comment by astuteo** [comment] 2021-02-24 02:35
@angrybrad Wait, I think you're right. When I map it to `results (x1)` it does seem to return the correct elements and function correctly. Consider my problem solved and sorry for the confusion.

**Comment by angrybrad** [comment] 2021-03-05 00:28
@astuteo awesome! Going to go ahead and close this out, then.

**Closed by angrybrad** 2021-03-05 00:28 UTC
Labels: bug
