### ISSUE TITLE
Not activating entries added back in the feed

### ISSUE THREAD

**Issue by bluestormdesign** [craftcms/feed-me#666] opened 2020-02-04 16:30 UTC
### Description

Feed me is set to disable missing elements, this bit works fine and disables all elements that are missing.

The problem I am having is if one of these disabled items are added back into the XML feed they are not enabled.

The only way I can get around this is to manually enable all entries related to the feed and run the feed again. This results in various things showing that I don't want showing!

I have set the default status to 'enabled' but this doesn't seem to make any different when it is being updated.

Is there anyway I can get Feed Me to re-enable the ones it disables?

There are no code examples because this is all handled internally by Craft!

### Steps to reproduce

1. With Feed Me add entries with disable if not found
2. Remove some of the entries from the feed, they will be disabled
3. Added the entries you just removed back in, they do get updated but the status doesn't change!

### Additional info

- Plugin version: 4.2.0
- Craft version: Craft Pro 3.3.19

**Comment by andersaloof** [comment] 2020-02-14 09:37
This seems related to my issue #659 filed 2 weeks ago.

Would be nice if this could be prioritized, as this creates lots of issues for our client at the moment when they have to manually activate products from a webshop feed whenever products are in stock again.

**Comment by bluestormdesign** [comment] 2020-02-14 09:40
@andersaloof the only way I could get around this is to have a <status>1</status> injected into every entry in the XML. That way you can setup feed me to use that field. Doing this will mean the entries that are updated will be enabled again. 

This seems like a hacking solution but it is the only work around I could find.

**Comment by jasondibenedetto** [comment] 2020-04-20 07:32
Currently running into this issue as well.

**Comment by angrybrad** [comment] 2020-11-07 01:04
This is most likely resolved in the just-released 4.3.0 if you want to give it a whirl. If it's still an issue, comment back here and we'll re-open.

**Comment by brettburwell** [comment] 2020-11-30 15:03
Hi y'all. I'm still seeing this issue running Feed Me 4.3.1.

**Comment by brettburwell** [comment] 2020-11-30 15:27
Thanks for reopening @angrybrad. If there's anything I can do to help with testing let me know.

**Comment by angrybrad** [comment] 2020-12-10 22:18
If the feed's status setting is set to "Use default value" and that default value is set to "enabled" then this works for me, which feels like the expected behavior. Make sure you're using those settings.

![CleanShot 2020-12-10 at 14 16 40](https://user-images.githubusercontent.com/61869/101836533-6a02d800-3af2-11eb-96e8-10ae6e0bce04.png)

**Comment by cole007** [comment] 2020-12-11 13:32
Sorry @angrybrad but in your above screenshot that seems to be when you don't want the import to determine the status.
What about if you do - eg have an import and reporting similar issues on Feed Me 4.3.1 for entries where a status value of 1 defined in the feed is not being respected on import and disabled entries in the CMS remain disabled (0)

**Comment by cole007** [comment] 2020-12-11 13:48
Think have identified the cause of the issue we are experiencing but not the solution - we are importing into multi-site but when the status is set to enabled the relevant record in Craft elements table is being set to 1 but the required value in the elements_sites table is not being set

**Comment by cole007** [comment] 2020-12-11 14:09
Sorry - to follow up some context:

1. The section I am importing into was set to disabled by default for the site I am importing into.
2. I updated the section so entries were enabled by default.
3. I have a parameter for my import set to 1 or 0 and the Entry Status against those in the Feed Me settings is set to use this for status
4. Re-importing using Feed-Me any entries previously marked as disabled remain so.

This seems odd behaviour - is there no current way to specify on a per-site basis status against an entry if that entry has already been imported (eg if feed is set to create or update)

**Comment by angrybrad** [comment] 2021-03-03 00:16
@cole007

>  is there no current way to specify on a per-site basis status against an entry if that entry has already been imported (eg if feed is set to create or update)

Unfortunately, that's currently correct in a multi-site setup. The "status" mapping in Feed Me is for the element's "global" status and there's not a per-site mapping.  

You could pull it off by listening to the [EVENT_STEP_BEFORE_ELEMENT_SAVE](https://docs.craftcms.com/feed-me/v4/developers/events.html#the-stepbeforeelementsave-event) event in a plugin/module and modifying the element's status on a per-site basis for your specific needs, too.

I've added a FR for this so it doesn't get lost here: https://github.com/craftcms/feed-me/issues/817

**Closed by angrybrad** 2021-03-03 00:16 UTC

**Comment by Lab385** [comment] 2025-04-14 02:51
Hiya, I'm getting the same issue with Feed Me not respecting the default status, so items returning to the XML feed remain as disabled entries after import.

Feed Me 5.11.0
Craft Solo 4.14.15
