### ISSUE TITLE
Support Matrix + Super Table nested importing

### ISSUE THREAD

**Issue by engram-design** [craftcms/feed-me#470] opened 2019-02-10 21:02 UTC

**Comment by keyurshah** [comment] 2019-06-05 16:54
i was using feedme to import into a super table inside a matrix and it only imported the first row of each supertable in a matrix block.

wondering what the best workaround would be until this is working. thanks!

**Comment by amityweb** [comment] 2019-06-15 15:59
Is there a solution for this? We wont be able to use super table inside a matrix if we can import into it. 

At the moment it creates a separate matrix entry with a ingle super table row in each, instead of one matrix entry and multiple super table rows. 

Thanks

**Comment by amityweb** [comment] 2019-07-08 22:25
The problem is because the $parsedValue array only contains the last super table row to import. Supr Table like Matrix takes arrays like:
```
[new1] => Array
        (
            [type] => 3
            [order] => 1
            [enabled] => 1
            [fields] => Array
                (
                    [accordionTitle] => My accordion title here
                    [accordionBody] => My text here
                )

        )

    [new2] => Array
        (
            [type] => 3
            [order] => 1
            [enabled] => 1
            [fields] => Array
                (
                    [accordionTitle] => My accordion title here
                    [accordionBody] => My text here
                )

        )
```

But actually only the last one is returned, so above only [new2] is returned, its not the full array. 

So I aded this dirty hack to get it working. This would not be the clean solution needed, but its got it working for me in case anyone else needs a quick solution:

Replace this line 113 in vendor/craft/feed-me/src/fields/Matrix.php:
`$parsedValue = $this->_parseSubField($nodePaths, $subFieldHandle, $subFieldInfo);`

With this code
```
			foreach($nodePaths AS $nodePathKey => $nodePathVal)
			{
				// Get the node number
				$pathArray = explode("/", $nodePathKey);
				$nodeNumber = $pathArray[count($pathArray)-2];
				$nodePathsArray[$nodeNumber][$nodePathKey] = $nodePathVal;
			}
			
			$i=1;
			$parsedValue = array();	
			foreach($nodePathsArray AS $nodePathsArrayKey => $nodePathsArrayValue)
			{
				$parsedValueTemp = $this->_parseSubField($nodePathsArrayValue, $subFieldHandle, $subFieldInfo);
            	$parsedValue["new".$i] = reset($parsedValueTemp);
            	$i++;
			}
```

**Comment by farezramilo** [comment] 2019-09-17 07:05
@amityweb Your code worked great! I just needed to place `$nodePathsArray = [];` above the first foreach to accommodate scenarios with multiple nested matrices because the contents eventually get mixed in that array.

**Comment by GaryReckard** [comment] 2019-12-06 14:27
This fix also worked for me. Thanks a lot @amityweb! 

Is this a FeedMe bug? Or is there another way to format my JSON to get this to work?  I love that it's working now... but I'm not too keen on hacking a plugin like this...

**Comment by amityweb** [comment] 2019-12-06 15:16
Either a FeedMe bug or just not supported yet. I imagine its just not supported in FeedMe, so its over to Craft to add that support.

**Comment by amityweb** [comment] 2019-12-06 15:18
In fact you can see Brandon added the enhancement label, so its on their list!

**Comment by jonXmack** [comment] 2019-12-10 13:52
Can anyone help me out with formatting my XML to get data imported into a supertable within a matrix? Currently I have the following, where pageBuilder is the matrix and pageBlock is each row.

```
<entries>
	<entry>
		<pageBuilder>
			<pageBlock>
				<superTable>
					<superTableRow>
						<heading></heading>
						<image></image>
						<thumb></thumb>
					</superTableRow>
				</superTable>
			</pageBlock>
		</pageBuilder>
	</entry>
</entries>
```

The above format works for regular Table fields, but not Super Table, as I get the message `Calling unknown method: craft\fields\Entries::getBlockTypeFields()` which implies it's trying to process the XML as an Entries field rather than a Super Table field

**Comment by arunbasnet** [comment] 2020-06-02 12:23
Anyone has got this working on Craft 3.4.16? I have the same problem and even though I replace the line pointed above, it does not change the way it is imported. i.e. I keep getting multiple Super Table blocks for each row rather than one Super Table block with multiple rows in them. 
![feedme-log-after-matrixfix](https://user-images.githubusercontent.com/51320564/83519602-93580100-a4dc-11ea-886e-112922926616.png)

**Comment by tekstrand** [comment] 2021-02-04 21:14
About to try using the code above for our data import. Would love to see this prioritized into the actual codebase!

**Comment by therealpecus** [comment] 2021-05-14 08:42
> The problem is because the $parsedValue array only contains one super table row to import. Super Table like Matrix takes arrays like:
> [...]
> So I aded this dirty hack to get it working. I just create a new parsedValue array with all the rows like above. This would not be the clean solution needed, but its got it working for me in case anyone else needs a quick solution:
> [...]

We've hit an edge case and I'm looking for support/help/insight.
We have a matrix field with 2 block types:
- one (`variantWithHotspots`) includes a supertable
- the other (`variantSimple`) doesn't

apart from this, fields in each block are identical

When importing, an image belonging to `variantSimple` block is assigned to the other block, and is eventually skipped. 
To clarify, an image from the `variantSimple` block type is assigned to the `variantWithHotspot` block and the block entry for variantSimple is skipped. So if we have an array of 1 variantWithHotspot and 2 variantSimple, we end up with:
- 1 variantWithHotspot (using fields from the first variantSimple block)
- 1 variantSimple

We're already resetting `$nodePathsArray = [];` per @farezramilo suggestion. Honestly, I haven't digged into the code, if anyone has a tip it's very welcome

**Closed** 2021-08-13 20:03 UTC
Labels: enhancement
