### ISSUE TITLE
Feed me `Trying to access array offset on value of type null`

### ISSUE THREAD

**Issue by prdanelli** [craftcms/feed-me#733] opened 2020-08-12 14:38 UTC
Firstly, thank you for investing time in this plugin, its been a really nice experience and saved me a bunch of copy-pasting.

### Description

During Feedme setup on the Mapping stage (/admin/feed-me/feeds/map/4), `FeedMeVariable::getSelectOptions` causes a `yii\base\ErrorException Exception`, "Trying to access array offset on value of type null", on Line `feed-me/src/web/twig/variables/FeedMeVariable.php:70` when assigning `$values[$value[$index]] = $value[$label];`. 

After some hunting through sections I narrowed down the issue to a matrix "Entries" field that had no Sources selected. I realise that this might not seem like a massive bug, however preventing the crash and not presenting a value in the field seems like a nicer way to handle this. 

I Added the following seems to prevent the crash: 

        if (is_array($options)) {
            foreach ($options as $key => $value) {
                # Adding the following if statement seems to resolve the issue for me
                if ($value && $value[$index]) {
                  $values[$value[$index]] = $value[$label];
                }
            }
        }

### Steps to reproduce

1. Set up Matrix with Entries field
2. Do NOT select Source and leave blank
3. Try to configure Feedme

### Additional info

- Craft version: 3.5.2
- PHP version: 7.4.6
- Database driver & version: mysql 5.7
- Plugins & versions: 4.2.3

**Comment by laurabennett** [comment] 2021-06-28 15:39
I am also running into the same error attempting to import Form fields from a Matrix.

**Comment by prdanelli** [comment] 2022-06-28 21:22
> @prdanelli - I just ran into this issue and your information saved me a bunch of time. Thank you

@magnessjo haha, I've not used Craft in a couple years now and had totally forgotten about this, but after a tricky day a kind message like this was just what I needed. 

I'm glad you got it sorted. :)

**Comment by i-just** [comment] 2023-01-23 15:45
I’m closing this one as there’s an updated version of this issue: #1186. It’s the same root cause. Feel free to follow along for updates there.

**Closed by i-just** 2023-01-23 15:45 UTC
Labels: bug
